### ISSUE TITLE
Unable to download comments

### ISSUE THREAD

**Issue by cboettig** [pathawks/jekyll-disqus-comments#1]
Thanks for sharing this project, was just thinking about trying to write something like this.  Looks very promising.

I just tried giving this a whirl to download my the disqus comments that currently appear on my Jekyll blog into a `_comments/` directory (hoping to use this to save my old comments while I transition to a static-email comments system).  

I register an application with Disqus to get a public API key as you indicate.  Then I clone this repo, add a `_config.yml` with the data indicated, create a `_comments` dir, and run `rake disquscomments` as indicated.

This executes without error (the only message is jekyll loading the config file), but nothing seems to happen, and `_comments` is still empty.  What did I miss? 

Many thanks for the help!

-- Carl (@cboettig)

p.s. I'm a bit confused about the workflow you envision here.  I imagine a one-time run that will extract all my disqus comments into local yaml files inside `_comments` that I can then embed into posts with liquid, following your example template in the `_includes` directory. It seems like you imagine a more continuous synchronizing between disqus and the local yaml?  Can you clarify this?

**Comment by pathawks** [comment]
Run `rake disquscomments --trace` and see if you get any error messages.

As far as the workflow, as more posts/comments are added, they will need to be downloaded at a later time. I imagine checking for new comments maybe each time a new post is published.

**Comment by pathawks** [comment]
Tell me, in your template, what ID are you passing to Disqus for each post?

The plugin assumes `{{ page.id }}`  
If you're using something else, that could be the trouble. `rake disquscomments` would not throw an error, because it would just assume there weren't any comments for that post.

**Comment by cboettig** [comment]
Ah, didn't have the template in place yet.  Now I get a proper error message; looks like it is not finding a match.  

``` bash
** Invoke disquscomments (first_time)
** Execute disquscomments
Configuration from /home/cboettig/Documents/code/thirdparty/jekyll-disqus-comments/_config.yml
Comments feed not found: /2008/06/09/PopBio-Core-Review-Notes
rake aborted!
undefined method `[]' for true:TrueClass
_rake/disqus_comments.rake:40:in `block (2 levels) in <top (required)>'
```

The post it refers to is the first one in my blog (I assume it didn't get any further). (Also it happens there are no comments on that page.) Perhaps I don't want `page.id`?  What are you matching page.id against in the diqus record?  Not sure where to begin trouble-shooting, but you can see what I'm looking at by cloning my [static-comments branch](https://github.com/cboettig/labnotebook/tree/static-comments) of my site repo; posts appear [here with disqus integration](http://carlboettiger.info/2008/06/09/PopBio-Core-Review-Notes) 

thanks for the help!

**Comment by pathawks** [comment]
Ok. It appears that you don't set a page ID for Disqus when calling it in the JavaScript on your site.  
This means that Disqus identifies the pages by their URL.

In order to get this to work in `disqus_comments.rake`, line 59 needs to be changed to something like

```
uri = "http://disqus.com/api/3.0/threads/listPosts.json?forum=#{siteid}&thread:link=#{ident}&api_key=#{api_key}&limit=100"
```

Lines 48 - 54 would need to be replaced with something like:

```
ident = site['url'] + post.data['url']
```

This can certainly be done, but I'm not really sure how to merge it so that it doesn't affect anything else.  
I would welcome a patch.

**Comment by lengerfulluse** [comment]
@pathawks there's no url field in my post.data. So i replace lines 48-54 with following line.   

```
ident = site['url'] + post.url  
```

But seems it still can not find the comments.   

``` ruby
--) rake disquscomments
/post/EasyMock-for-unit-test   # just dump the post.url field.
Comments feed not found: /post/EasyMock-for-unit-test
/post/Controller-View-Model
Comments feed not found: /post/Controller-View-Model
/post/Facade-Design-Pattern
Comments feed not found: /post/Facade-Design-Pattern
```

**Comment by pathawks** [comment]
You are not passing an absolute URL to Disqus, which I imagine is why it is choking.

**Comment by lengerfulluse** [comment]
No, since the `ident` i used is:      

```
  ident = site['url'] + post.url   
```

The above log just printed the `post.url`, which maybe confusing. The actual request i sent was as following:  

``` ruby
http://disqus.com/api/3.0/threads/listPosts.json?forum=***&thread:link=http://t.hengwei.me/post/java-exception-programming-practice&api_key=***&limit=100
Comments feed not found: /post/java-exception-programming-practice

http://disqus.com/api/3.0/threads/listPosts.json?forum=***&thread:link=http://t.hengwei.me
/post/%25E6%25B5%2585%25E8%25B0%2588l0l1l2%25E8%258C%2583%25E6%2595%25B0%25E5%258F%258A%25E5%2585%25B6%25E5%25BA%2594%25E7%2594%25A8&api_key=***&limit=100
Comments feed not found: /post/浅谈l0l1l2范数及其应用

http://disqus.com/api/3.0/threads/listPosts.json?forum=***&thread:link=http://t.hengwei.me/post/%25E6%25A0%25B8%25E5%2587%25BD%25E6%2595%25B0%25E4%25B8%258E%25E6%259425AF%25E6%258C%2581%25E5%2590%2591%25E9%2587%258F%25E6%259C%25BA%25E5%2585%25A5%25E9%2597%25A8&api_key=***&limit=100
```

**Comment by lengerfulluse** [comment]
Oh, I found the problem. If you use the `thread:link` instead of `thread:ident`, you'd better make sure there's a suffix slash `\` at the end of the link.  It sounds weird. But when i tested it via their console(https://disqus.com/api/console/?endpoint=%2FlistPosts#!/), it proved that a suffix slash `/` is necessary.  Also you can use the listThread(https://disqus.com/api/console/?endpoint=%2FlistThreads#!/) API to found the actual thread:link format stored in disqus side.  
Just resolved it. Thanks guys.
